# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password_generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import random
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 349)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(120, 40, 171, 21))
        self.password.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 80, 41, 16))
        self.label_2.setObjectName("label_2")
        self.length = QtWidgets.QSpinBox(self.centralwidget)
        self.length.setGeometry(QtCore.QRect(120, 80, 42, 22))
        self.length.setObjectName("length")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 81, 16))
        self.label_3.setObjectName("label_3")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(120, 120, 111, 21))
        self.name.setObjectName("name")
        self.symbol_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.symbol_checkbox.setGeometry(QtCore.QRect(210, 70, 70, 17))
        self.symbol_checkbox.setObjectName("symbol_checkbox")
        self.symbol_checkbox.setChecked(True)
        self.uppercase_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.uppercase_checkbox.setGeometry(QtCore.QRect(210, 90, 81, 17))
        self.uppercase_checkbox.setObjectName("uppercase_checkbox")
        self.uppercase_checkbox.setChecked(True)
        self.numbers_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.numbers_checkbox.setGeometry(QtCore.QRect(280, 70, 70, 17))
        self.numbers_checkbox.setObjectName("numbers_checkbox")
        self.numbers_checkbox.setChecked(True)
        self.create = QtWidgets.QPushButton(self.centralwidget)
        self.create.setGeometry(QtCore.QRect(160, 160, 75, 23))
        self.create.setObjectName("create")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(290, 270, 75, 23))
        self.exit.setObjectName("exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 380, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.create.clicked.connect(self.generate_password) # type: ignore
        self.exit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # The password generator function
    def generate_password(self):
        length = int(self.length.text()) # the str() was making problem
        name = self.name.text()
        
        characters = "abcdefghijklmnopqrstuvwxyz"
        symbols = "!@#$%^&*()_+"
        upperCase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        numbers = "0123456789"

        # Add symbols and uppercase based on checkbox status

        if self.symbol_checkbox.isChecked():
            characters += symbols
        
        if self.uppercase_checkbox.isChecked():
            characters+= upperCase

        if self.numbers_checkbox.isChecked():
            characters+=numbers

        password = "".join(random.sample(characters, length-len(name)))
        passwordWithName = name + password 

        self.password.setText(passwordWithName)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Password Generator"))
        self.password.setText(_translate("MainWindow", "This will be your password"))
        self.label.setText(_translate("MainWindow", "Your Password:"))
        self.label_2.setText(_translate("MainWindow", "length:"))
        self.label_3.setText(_translate("MainWindow", "Name(optional):"))
        self.symbol_checkbox.setText(_translate("MainWindow", "Symbols"))
        self.uppercase_checkbox.setText(_translate("MainWindow", "Upper case"))
        self.numbers_checkbox.setText(_translate("MainWindow", "Numbers"))
        self.create.setText(_translate("MainWindow", "Create"))
        self.exit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
